export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Air Fryer Pro 5L',
    slug: 'air-fryer-pro-5l',
    description: 'Professional grade air fryer with 5L capacity and precision temperature control.',
    price: 129.99,
    salePrice: 99.99,
    onSale: true,
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1625937286074-9ca519d5d9df?auto=format&fit=crop&w=500&q=80',
    rating: 4.8,
    reviewsCount: 124,
    stock: 15,
  },
  {
    id: '2',
    name: 'Ergonomic Mesh Office Chair',
    slug: 'ergonomic-mesh-office-chair',
    description: 'High-back mesh chair with lumbar support for ultimate comfort during long work hours.',
    price: 249.00,
    salePrice: 189.00,
    onSale: true,
    category: 'office',
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=500&q=80',
    rating: 4.6,
    reviewsCount: 89,
    stock: 10,
  },
  {
    id: '3',
    name: 'True Wireless Noise-Cancelling Buds',
    slug: 'true-wireless-buds',
    description: 'Experience pure sound with active noise cancellation and 30-hour battery life.',
    price: 129.99,
    salePrice: null,
    onSale: false,
    category: 'tech',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=500&q=80',
    rating: 4.8,
    reviewsCount: 210,
    stock: 45,
  },
  {
    id: '4',
    name: 'Smart Coffee Maker',
    slug: 'smart-coffee-maker',
    description: 'Wake up to the perfect brew with programmable settings and smart app control.',
    price: 149.50,
    salePrice: 120.00,
    onSale: true,
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=500&q=80',
    rating: 4.7,
    reviewsCount: 56,
    stock: 8,
  },
  {
    id: '5',
    name: 'RGB Mechanical Gaming Keyboard',
    slug: 'rgb-mechanical-keyboard',
    description: 'Ultra-responsive mechanical switches with customizable RGB lighting and macros.',
    price: 89.00,
    salePrice: null,
    onSale: false,
    category: 'gaming',
    image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?auto=format&fit=crop&w=500&q=80',
    rating: 4.5,
    reviewsCount: 72,
    stock: 20,
  },
  {
    id: '6',
    name: '2K HD Outdoor Security Camera',
    slug: '2k-hd-security-camera',
    description: 'Keep your home safe with high-definition night vision and AI motion detection.',
    price: 89.99,
    salePrice: 69.99,
    onSale: true,
    category: 'security',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93L88?auto=format&fit=crop&w=500&q=80',
    rating: 4.7,
    reviewsCount: 112,
    stock: 12,
  },
];
